config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :seances, only: [:new, :create, :index, :show]
  post '/favorites/toggle', to: 'favorites#toggle'
  resources :favorites, only: [:new, :create, :index, :destroy]
  resources :profiles, only: [:show]
  resources :user_platforms, only: [:new, :create, :destroy]
  get 'seances/:id/:type/streaming_platforms', to: 'seances#show_streaming_platforms', as: :streaming_platforms
  match '*path', to: 'errors#not_found', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/models/seance.rb
class Seance < ApplicationRecord
  belongs_to :user
  validates :seance_type, presence: true, inclusion: { in: ['Film', 'Série'] }
  attr_accessor :search_type
end

app/controllers/seances_controller.rb
require 'httparty'

class SeancesController < ApplicationController
  include PlatformHelper

  def index
    @seances = Seance.all
    authorize @seances
  end

  def show
    item_id = params[:id]
    tmdb_service = ThemoviedbService.new(api_key)
    seance_type = params[:type]

    if seance_type == 'film'
      @item_details = tmdb_service.get_movie_details(item_id)
      if @item_details
        authorize :movie, :show?
      else
        redirect_to seances_path, alert: "Ce film n'existe pas."
        return
      end
    elsif seance_type == 'serie'
      @item_details = tmdb_service.get_series_details(item_id)
      if @item_details
        authorize :series, :show?
      else
        redirect_to seances_path, alert: "Cette série n'existe pas."
        return
      end
    else
      authorize :seance, :show?
      redirect_to seances_path, alert: "Type de média non spécifié ou non valide."
      return
    end
    @item_in_favorites = Favorite.find_by(tmdb_id: @item_details["id"], user_id: current_user.id)

  end



  def new
    @seance = Seance.new
    flash.now[:alert] = flash[:alert] if flash[:alert].present?
    @genres = fetch_genres
    @origin_country = fetch_origin_countries
    @actors = fetch_popular_actors
    @runtime = []
    authorize @seance
  end



  def create
    @seance = Seance.new(seance_params)
    tmdb_service = ThemoviedbService.new(api_key)
    preferences = build_preferences_hash(params[:seance])
    user = current_user
    user_region = detect_user_region
    authorize @seance
    query_params = {}

    watch_region = params[:seance][:watch_region]

    watch_provider_ids = user.selected_platforms.map do |platform|
      hash = eval(platform)
      hash[:id]
    end

    if params[:seance][:seance_type].blank?
      redirect_to new_seance_path, flash: { alert: "Veuillez sélectionner un type de média (Film ou Série)." }
      return
    end

    if params[:seance][:seance_type] == 'Film'
      session[:recommendations] = tmdb_service.recommend_movies(preferences, user, user_region, watch_provider_ids).first(20).map do |recommendation|
        recommendation.merge({ "media_type" => "film" })
      end
    elsif params[:seance][:seance_type] == 'Série'
      session[:recommendations] = tmdb_service.recommend_series(preferences, user, user_region, watch_provider_ids).first(20).map do |recommendation|
        recommendation.merge({ "media_type" => "serie" })
      end
    end

    if session[:recommendations].nil? || session[:recommendations].empty?
      redirect_to new_seance_path, flash: { alert: "Nous n'avons pas trouvé votre bonheur... Veuillez réessayer" }
      return
    end
    watch_providers_param = watch_provider_ids.join('|')

    redirect_to seances_path
  end


  def show_streaming_platforms
    item_id = params[:id]
    seance_type = params[:type] == 'film' ? 'movie' : 'tv'
    tmdb_service = ThemoviedbService.new(api_key)

    @item_details = seance_type == 'movie' ? tmdb_service.get_movie_details(item_id) : tmdb_service.get_series_details(item_id)

    if @item_details
      @streaming_providers = tmdb_service.get_streaming_providers(item_id, seance_type)

      user_streaming_ids = current_user.selected_platforms.map do |platform_string|
        platform_hash = eval(platform_string)
        platform_hash[:id]
      end

      @available_platforms = @streaming_providers.select do |provider|
        user_streaming_ids.include?(provider["provider_id"].to_i)
      end

      @available_platforms.uniq! { |platform| platform["provider_id"] }
      authorize Seance
    else
      redirect_to seances_path, alert: 'Détails non trouvés.'
      return
    end
  end

  def search_actors
    search_query = params[:query]
    tmdb_service = ThemoviedbService.new(ENV['TMDB_API_KEY'])
    actors = tmdb_service.search_actors(query)
    render json: actors
  end


  private


  def fetch_genres
    tmdb_service = ThemoviedbService.new(api_key)
    tmdb_service.get_all_genres
  end

  def fetch_popular_actors
    tmdb_service = ThemoviedbService.new(api_key)
    tmdb_service.get_popular_actors
  end

  def fetch_origin_countries
    tmdb_service = ThemoviedbService.new(api_key)
    tmdb_service.get_countries
  end

  def build_preferences_hash(seance_params)
    {
      genre: seance_params[:genre],
      runtime: seance_params[:runtime],
      keyword: seance_params[:keyword],
      actor: seance_params[:actor],
      year: seance_params[:year],
      origin_country: seance_params[:origin_country],
    }
  end

  def api_key
    ENV['TMDB_API_KEY']
  end

  def set_seance
    @seance = Seance.find(params[:id])
  end


  def seance_params
    params.require(:seance).permit(:genre, :keyword, :user_id, :seance_type, :actor, :year, :watch_region, :runtime, :origin_country)
  end



  def detect_user_region
    response = HTTParty.get("https://ipapi.co/json/")
    if response.success?
      JSON.parse(response.body)['country_code']
    else
      'US'
    end
  end
end

app/views/seances/index.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> <%= DEFAULT_META["title"] %> </title>
</head>

<body>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500&display=swap" rel="stylesheet">
<div class="movie-screen-final">
    <% if session[:recommendations] %>
      <% session[:recommendations].each do |movie| %>
      <turbo-frame id="movie-frame-<%= movie['id'] %>">
        <div class="movie-card movie-card-<%= movie['id'] %>" data-controller="movie-card" data-url="<%= streaming_platforms_path(id: movie['id'], type: movie['media_type']) %>" data-card-id="<%= movie['id'] %>" data-action="swipe-left->movie-card#swipeLeft">
          <div class="card-inner">
            <div class="card-front">
              <%= image_tag("https://image.tmdb.org/t/p/w500/#{movie["poster_path"]}",
                class: "rectangle",
                srcset: "https://image.tmdb.org/t/p/w300/#{movie["poster_path"]} 300w,
                https://image.tmdb.org/t/p/w500/#{movie["poster_path"]} 500w",
                sizes: "(max-width: 768px) 300px, 500px",
                onload: "this.parentElement.style.background='none'",
                loading: "lazy") %>

            <div class="favorite-container"
              data-controller="favorite"
              data-favorite-id-value="<%= movie['id'] %>"
              data-favorite-title-value="<%= movie['title'] || movie['name'] %>"
              data-favorite-image-url-value="<%= movie["poster_path"] %>"
              data-favorite-media-type-value="<%= movie["media_type"] %>">

              <input type="checkbox" class="checkbox" id="favorite-checkbox-<%= movie['id'] %>"
                data-action="change->favorite#toggle"
                <%= 'checked' if current_user.movie_in_favorites?(movie['id']) %>>
              <label for="favorite-checkbox-<%= movie['id'] %>">
                <svg id="heart-svg" viewBox="467 392 58 57" xmlns="http://www.w3.org/2000/svg">
                <g id="Group" fill="none" fill-rule="evenodd" transform="translate(467 392)">
                <path id="heart" d="M29.144 20.773c-.063-.13-4.227-8.67-11.44-2.59C7.63 28.795 28.94 43.256 29.143 43.394c.204-.138 21.513-14.6 11.44-25.213-7.214-6.08-11.377 2.46-11.44 2.59z" fill="#FFFFFF"/>
                <circle id="main-circ" fill="#E2264D" opacity="0" cx="29.5" cy="29.5" r="1.5"/>

                <g id="grp7" opacity="0" transform="translate(7 6)">
                  <circle id="oval1" fill="#9CD8C3" cx="2" cy="6" r="2"/>
                  <circle id="oval2" fill="#8CE8C3" cx="5" cy="2" r="2"/>
                </g>

                <g id="grp6" opacity="0" transform="translate(0 28)">
                  <circle id="oval1" fill="#CC8EF5" cx="2" cy="7" r="2"/>
                  <circle id="oval2" fill="#91D2FA" cx="3" cy="2" r="2"/>
                </g>

                <g id="grp3" opacity="0" transform="translate(52 28)">
                  <circle id="oval2" fill="#9CD8C3" cx="2" cy="7" r="2"/>
                  <circle id="oval1" fill="#8CE8C3" cx="4" cy="2" r="2"/>
                </g>

                <g id="grp2" opacity="0" transform="translate(44 6)">
                  <circle id="oval2" fill="#CC8EF5" cx="5" cy="6" r="2"/>
                  <circle id="oval1" fill="#CC8EF5" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp5" opacity="0" transform="translate(14 50)">
                  <circle id="oval1" fill="#91D2FA" cx="6" cy="5" r="2"/>
                  <circle id="oval2" fill="#91D2FA" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp4" opacity="0" transform="translate(35 50)">
                  <circle id="oval1" fill="#F48EA7" cx="6" cy="5" r="2"/>
                  <circle id="oval2" fill="#F48EA7" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp1" opacity="0" transform="translate(24)">
                  <circle id="oval1" fill="#9FC7FA" cx="2.5" cy="3" r="2"/>
                  <circle id="oval2" fill="#9FC7FA" cx="7.5" cy="2" r="2"/>
                </g>
              </g>
              </svg>
              </label>
            </div>
            </div>
            <div class="card-back">
              <div class="movie-details">
                <div class="movie-title-section">
                  <%= image_tag('camera2.svg', class: 'camera-icon') %>
                  <div class="camera-icon">
                    <div class="movie-title-section">
                      <h2 class="movie-title"><%= (movie["title"] || movie["name"]).upcase %></h2>
                      <p class="movie-year">Année de production : <%= (movie["release_date"] || movie["first_air_date"]).to_s.split("-").first %></p>
                      <p class="movie-vote">Vote du public : <%= movie["vote_average"] %> / 10</p>
                    </div>
                  </div>
                </div>
                <div class="movie-description-section">
                  <div class="movie-overview">
                    <div class="overview-container">
                      <p class="overview-text"><%= movie["overview"] %></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="favorite-container"
              data-controller="favorite"
              data-favorite-id-value="<%= movie['id'] %>"
              data-favorite-title-value="<%= movie['title'] || movie['name'] %>"
              data-favorite-image-url-value="<%= movie["poster_path"] %>"
              data-favorite-media-type-value="<%= movie["media_type"] %>">

              <input type="checkbox" class="checkbox" id="favorite-checkbox-back-<%= movie['id'] %>"
                data-action="change->favorite#toggle"
                <%= 'checked' if current_user.movie_in_favorites?(movie['id']) %>>
              <label for="favorite-checkbox-back-<%= movie['id'] %>">
                <svg id="heart-svg" viewBox="467 392 58 57" xmlns="http://www.w3.org/2000/svg">
                <g id="Group" fill="none" fill-rule="evenodd" transform="translate(467 392)">
                <path id="heart" d="M29.144 20.773c-.063-.13-4.227-8.67-11.44-2.59C7.63 28.795 28.94 43.256 29.143 43.394c.204-.138 21.513-14.6 11.44-25.213-7.214-6.08-11.377 2.46-11.44 2.59z" fill="#FFFFFF"/>
                <circle id="main-circ" fill="#E2264D" opacity="0" cx="29.5" cy="29.5" r="1.5"/>

                <g id="grp7" opacity="0" transform="translate(7 6)">
                  <circle id="oval1" fill="#9CD8C3" cx="2" cy="6" r="2"/>
                  <circle id="oval2" fill="#8CE8C3" cx="5" cy="2" r="2"/>
                </g>

                <g id="grp6" opacity="0" transform="translate(0 28)">
                  <circle id="oval1" fill="#CC8EF5" cx="2" cy="7" r="2"/>
                  <circle id="oval2" fill="#91D2FA" cx="3" cy="2" r="2"/>
                </g>

                <g id="grp3" opacity="0" transform="translate(52 28)">
                  <circle id="oval2" fill="#9CD8C3" cx="2" cy="7" r="2"/>
                  <circle id="oval1" fill="#8CE8C3" cx="4" cy="2" r="2"/>
                </g>

                <g id="grp2" opacity="0" transform="translate(44 6)">
                  <circle id="oval2" fill="#CC8EF5" cx="5" cy="6" r="2"/>
                  <circle id="oval1" fill="#CC8EF5" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp5" opacity="0" transform="translate(14 50)">
                  <circle id="oval1" fill="#91D2FA" cx="6" cy="5" r="2"/>
                  <circle id="oval2" fill="#91D2FA" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp4" opacity="0" transform="translate(35 50)">
                  <circle id="oval1" fill="#F48EA7" cx="6" cy="5" r="2"/>
                  <circle id="oval2" fill="#F48EA7" cx="2" cy="2" r="2"/>
                </g>

                <g id="grp1" opacity="0" transform="translate(24)">
                  <circle id="oval1" fill="#9FC7FA" cx="2.5" cy="3" r="2"/>
                  <circle id="oval2" fill="#9FC7FA" cx="7.5" cy="2" r="2"/>
                </g>
              </g>
              </svg>
              </label>
            </div>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </turbo-frame>
  <div id="end-of-cards-message">
    <p>Vous avez vu toutes les recommandations.</p>
    <button class="btn_restart" onclick="location.href='<%= new_seance_path %>'">
      Recommencer
    </button>
  </div>
</div>
<script>
document.addEventListener("DOMContentLoaded", function () {
  const descriptions = document.querySelectorAll(".movie-overview");
  descriptions.forEach((description) => {
    if (description.scrollHeight > description.clientHeight) {
      description.classList.add("auto-scroll");
    }
  });
});
</script>
</body>

app/views/seances/new.html.erb
<div class="form-screen container-fluid ">
  <div class="row justify-content-center align-items-center">
    <div class="col p-0">
      <h1 class="title">MES PREFERENCES</h1>
      <%= simple_form_for @seance, html: { class: 'custom-form' } do |f| %>
      <div class="hiding-logic">
        <div class="form-group">
          <%= f.input :seance_type, collection: ['Film', 'Série'], prompt: 'Sélectionnez un type', input_html: { class: 'form-control seance_type', required: 'required' }, label_html: { class: 'custom-label' }, label: "<span style='color: white;'>Type</span>".html_safe %>
        </div>

        <div class="form-group" id="genre-input">
          <%= f.input :genre, label: "<span style='color: white;'>Genre</span>".html_safe, collection: @genres, prompt: 'Sélectionnez un genre', input_html: { class: 'form-control seance_genre'  }, label_html: { class: 'custom-label' } %>
        </div>

        <div class="form-group" id="keyword-input" style="display: none;">
          <%= f.input :keyword, label: "<span style='color: white;'>Mot Clé</span>".html_safe, input_html: { class: 'form-control' }, label_html: { class: 'custom-label' } %>
        </div>

        <div class="form-group">
          <div class="form-check-group">
            <div class="form-check-group">
              <%= f.radio_button :search_type, 'genre', id: 'search-by-genre', checked: true %>
              <%= f.label :search_type_genre, 'Rechercher par genre' %>
            </div>
            <div class="form-check-group">
              <%= f.radio_button :search_type, 'keyword', id: 'search-by-keyword' %>
              <%= f.label :search_type_keyword, 'Rechercher par mot-clé' %>
            </div>
          </div>
        </div>
      </div>
      <div class="form-group">
        <a href="#" id="advanced-search-toggle" class="advanced-search-link mb-5">
          recherche avancée
          <svg class="search-icon" width="18" height="18" viewBox="0 0 18 18" fill="none"
            xmlns="http://www.w3.org/2000/svg">
            <path
              d="M13.2878 11.0014H12.4935L12.212 10.7314C12.8403 10.0054 13.2995 9.15021 13.5568 8.22705C13.814 7.30389 13.8629 6.33559 13.7 5.39144C13.2274 2.61144 10.8949 0.39144 8.07976 0.0514397C7.09006 -0.0730946 6.08483 0.0292113 5.14099 0.350529C4.19715 0.671846 3.33973 1.20366 2.63432 1.90527C1.92891 2.60688 1.39423 3.4597 1.07117 4.39846C0.748119 5.33723 0.64526 6.33706 0.770468 7.32144C1.11231 10.1214 3.34431 12.4414 6.13933 12.9114C7.08859 13.0735 8.06213 13.0248 8.99027 12.769C9.91842 12.5131 10.7782 12.0564 11.5082 11.4314L11.7797 11.7114V12.5014L16.0526 16.7514C16.4648 17.1614 17.1385 17.1614 17.5507 16.7514C17.9629 16.3414 17.9629 15.6714 17.5507 15.2614L13.2878 11.0014ZM7.25533 11.0014C4.75187 11.0014 2.73101 8.99144 2.73101 6.50144C2.73101 4.01144 4.75187 2.00144 7.25533 2.00144C9.75879 2.00144 11.7797 4.01144 11.7797 6.50144C11.7797 8.99144 9.75879 11.0014 7.25533 11.0014Z"
              fill="white" />
          </svg>
        </a>
        <div id="advanced-search-fields" style="display: none;">

          <div class="form-group">
            <%= f.input :year, label: 'Année', as: :select, collection: (1980..2024).to_a.reverse, prompt: 'Sélectionnez une année', input_html: { class: 'form-control' }, label_html: { class: 'custom-label' } %>
            <%= f.input :actor, label: 'Acteur', collection: @actors, prompt: 'Sélectionnez un acteur', input_html: { class: 'form-control' }, label_html: { class: 'custom-label' } %>
            <%= f.input :runtime, label: 'Durée', collection: [['Moins de 60 min', 60], ['Moins de 90 min', 90], ['Moins de 120 min', 120]], prompt: 'Sélectionnez une durée', input_html: { class: 'form-control' }, label_html: { class: 'custom-label' } %>
            <%= f.input :origin_country, label: "Pays d'origine", collection: @origin_country, prompt: 'Sélectionnez un pays', input_html: { class: 'form-control' }, label_html: { class: 'custom-label' }  %>
          </div>
        </div>

        <%= f.submit "Rechercher", class: "btn search" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="ellipse ellipse-left"></div>
<div class="ellipse ellipse-right"></div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
  $(document).ready(function () {
    $('#advanced-search-toggle').click(function (e) {
      e.preventDefault();
      $('#advanced-search-fields').slideToggle(400);
      $('.hiding-logic').toggle();
    });
  });
</script>

<script>
  $(document).ready(function () {
    function toggleInputs() {
      if ($('#search-by-genre').is(':checked')) {
        $('#genre-input').slideDown(400);
        $('#keyword-input').slideUp(400);
        $('#seance_keyword').prop('disabled', true);
        $('#seance_genre').prop('disabled', false);
      } else {
        $('#genre-input').slideUp(400);
        $('#keyword-input').slideDown(400);
        $('#seance_keyword').prop('disabled', false);
        $('#seance_genre').prop('disabled', true);
      }
    }

    toggleInputs();

    $('input[name="seance[search_type]"]').change(function () {
      toggleInputs();
    });
  });
</script>

app/views/seances/show.html.erb
<div class="container rounded-circle">
  <div class="row mt-4">
    <div class="col d-flex flex-column align-items-center">
      <% Rails.logger.debug "Item Details: #{@item_details}" %>
      <% if @item_details.present? %>
        <%= image_tag("https://image.tmdb.org/t/p/w500/#{@item_details["poster_path"]}", alt: "#{@item_details["title"] || @item_details["name"]} poster", class: "img-fluid") %>
      <% else %>
        <p>Détails non disponibles.</p>
      <% end %>

      <% if @item_in_favorites %>
        <%= button_to favorite_path(@item_in_favorites), method: :delete, html: { class: "mt-3 ml-auto" } do %>
          <i class="fa-solid fa-heart"></i>
        <% end %>
      <% else %>
        <%= button_to favorites_path, method: :post, params: { tmdb_id: @item_details["id"], media_type: @item_details["media_type"], title: @item_details["title"], image_url: @item_details["poster_path"] }, html: { class: "mt-3 ml-auto" } do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/seances/show_streaming_platforms.html.erb
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
<div class="validation-screen">
  <img src="<%= image_path('bobine.svg') %>" class="film-reel left" alt="Bobine de film gauche">
  <img src="<%= image_path('bobine.svg') %>" class="film-reel right" alt="Bobine de film droite">
  <div class="platforms-container">
    <% if @available_platforms.any? %>
    <% @available_platforms.each do |platform| %>
    <div class="provider">
      <%= link_to(platform_logo(platform["name"]), platform["url"], target: "_blank") %>
    </div>
    <% end %>
    <% else %>
    <p class="no-platforms">No streaming platforms are available for this content.</p>
    <% end %>
  </div>
  <div class="session-text">Bonne Séance !</div>
</div>
</body>