config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :seances, only: [:new, :create, :index, :show]
  post '/favorites/toggle', to: 'favorites#toggle'
  resources :favorites, only: [:new, :create, :index, :destroy]
  resources :profiles, only: [:show]
  resources :user_platforms, only: [:new, :create, :destroy]
  get 'seances/:id/:type/streaming_platforms', to: 'seances#show_streaming_platforms', as: :streaming_platforms
  match '*path', to: 'errors#not_found', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/controllers/user_platforms_controller.rb
class UserPlatformsController < ApplicationController
  include PlatformHelper

  def new
    @user_platform = UserPlatform.new
    set_user_streaming_ids
    @platforms = Platform.all
    authorize @user_platform
  end

  def create
    platform_names = params[:user][:selected_platforms].reject(&:blank?)
    selected_platforms = platform_names.map do |name|
      { name: name, id: map_watch_provider_to_id(name) }
    end

    current_user.update(selected_platforms: selected_platforms)
    if current_user.save
      redirect_to new_seance_path, notice: "Vos sélections de plateformes ont été enregistrées."
    else
      render :new
    end
    authorize current_user, :create?

    rescue NoMethodError
    flash[:alert] = 'Vous devez au moins selectionner une plateforme'
    redirect_to new_user_platform_path
    authorize current_user, :create?
  end

  private

  def user_platform_params
    params.require(:user).permit(platform_ids: [])
  end
end

app/views/user_platforms/new.html.erb
<div class="container-fluid main-container background-standard">
  <div class="row justify-content-center align-items-center">
    <div class="col  px-0">
      <div class="second-container">
        <div class="profile-header">
          <%= link_to :back, class: "m-4 back-button" do %>
          <img src="<%= image_path('back.png') %>" alt="back" class="nav-icon">
          <% end %>
          <h3 class="title-profile-style text-center mt-5">Mes plateformes</h3>
        </div>
        <div class="profile-body text-center">
          <div class="text-center profile-avatar">
            <%= image_tag(current_user.avatar, class: "avatar-large", alt: "avatar")%>
          </div>
          <%= form_with(model: current_user, url: user_platforms_path, method: :post, local: true) do |f| %>
          <div data-controller="platform">
            <div class="d-flex justify-content-center flex-wrap mx-4">
              <% PLATFORMS.each_with_index do |provider_name, index| %>
              <div class="platform-selection mb-5">
                <%= image_tag "#{provider_name[:name].downcase.gsub(' ', '_')}_logo.png",
                    alt: "#{provider_name[:name]} logo",
                    class: "mx-2 platform-logo #{@user_streaming_ids.include?(provider_name[:id])? 'selected': 'unselected'}",
                    data: { action: "click->platform#toggleSelection", platform: provider_name[:name], platform_target: "platform" } %>
            <%= f.hidden_field :selected_platforms,
                  name: 'user[selected_platforms][]',
                  value: provider_name[:name],
                  id: "hiddenField#{index}",
                  disabled: !@user_streaming_ids.include?(provider_name[:id]),
                  data: { platform: provider_name[:name], platform_target: "hiddenField" } %>
          </div>
              <% end %>
            </div>
          </div>
          <div class="d-flex justify-content-center mt-3 mb-5">
            <%= f.submit "Enregistrer", class:"button-standard mt-2"%>
          </div>
          <% end %>
          <div class="profile-footer">
          </div>
        </div>
      </div>
    </div>
  </div>
</div>