config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations" }
  root to: "pages#home"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html


  resources :seances, only: [:new, :create, :index, :show]
  post '/favorites/toggle', to: 'favorites#toggle'
  resources :favorites, only: [:new, :create, :index, :destroy]
  resources :profiles, only: [:show]
  resources :user_platforms, only: [:new, :create, :destroy]
  get 'seances/:id/:type/streaming_platforms', to: 'seances#show_streaming_platforms', as: :streaming_platforms
  match '*path', to: 'errors#not_found', via: :all, constraints: lambda { |req| req.path.exclude? 'rails/active_storage' }
  get '/500', to: 'errors#internal_server_error', as: :internal_server_error
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div data-controller="alert">
    <div class="alert alert-info alert-dismissible fade show m-1" role="alert" data-action="click->alert#closeAlert">
      <%= notice %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  </div>
<% end %>
<% if alert %>
  <div data-controller="alert">
    <div class="alert alert-warning alert-dismissible fade show m-1" role="alert" data-action="click->alert#closeAlert">
      <%= alert %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
      </button>
    </div>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mb-4">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Favorites", favorites_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true"
            aria-expanded="false">
            <%= image_tag(current_user.avatar, class: "avatar", alt: "dropdown menu") %>
          </a>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Profil", profile_path(current_user), class: "dropdown-item" %>
            <%= link_to "Platform", new_user_platform_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
          </div>
        </li>
        <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="navbar-nav-mobile  navbar-dark bg-dark mt-4">
  <%= link_to new_seance_path, class: "nav-link text-light" do %>
  <img src="<%= image_path('home.jpg') %>" alt="home" class="nav-icon">
  <% end %>

  <%= link_to favorites_path, class: "nav-link text-light" do%>
 <img src="<%= image_path('favorite_full.jpg') %>" alt="coeur" class="nav-icon">
  <% end %>
<% if user_signed_in? %>
  <%= link_to profile_path(current_user), class: "nav-link text-light" do %>
  <img src="<%= image_path('user.jpg') %>" alt="user" class="nav-icon">
  <% end %>
<% end %>
</div>